// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0lvk_dAOwbTD8NnwmVdnw1qwlXiTBk1M',
    appId: '1:921639564558:web:94472c47bbea59a53f935f',
    messagingSenderId: '921639564558',
    projectId: 'ntclibrary-602d1',
    authDomain: 'ntclibrary-602d1.firebaseapp.com',
    storageBucket: 'ntclibrary-602d1.firebasestorage.app',
    measurementId: 'G-5WZTESGS5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPqqmnerYhYe-AeWJy49bzGbNwi4vt34',
    appId: '1:921639564558:android:173a6178b969530c3f935f',
    messagingSenderId: '921639564558',
    projectId: 'ntclibrary-602d1',
    storageBucket: 'ntclibrary-602d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVvn08dgX7zjyQat6o8pegjxMiRd5FMvk',
    appId: '1:921639564558:ios:a1fbb3c5d519c4793f935f',
    messagingSenderId: '921639564558',
    projectId: 'ntclibrary-602d1',
    storageBucket: 'ntclibrary-602d1.firebasestorage.app',
    iosBundleId: 'com.example.ntcLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVvn08dgX7zjyQat6o8pegjxMiRd5FMvk',
    appId: '1:921639564558:ios:a1fbb3c5d519c4793f935f',
    messagingSenderId: '921639564558',
    projectId: 'ntclibrary-602d1',
    storageBucket: 'ntclibrary-602d1.firebasestorage.app',
    iosBundleId: 'com.example.ntcLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0lvk_dAOwbTD8NnwmVdnw1qwlXiTBk1M',
    appId: '1:921639564558:web:74a3de0beefe00463f935f',
    messagingSenderId: '921639564558',
    projectId: 'ntclibrary-602d1',
    authDomain: 'ntclibrary-602d1.firebaseapp.com',
    storageBucket: 'ntclibrary-602d1.firebasestorage.app',
    measurementId: 'G-3KZ15KV9PS',
  );
}
